workflows:
  ios-workflow:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple
      vars:
        BUNDLE_ID: com.orizg.lift14
    scripts:
      - name: Set up keychain to be active
        script: |
          keychain initialize
      - name: Fetch signing files (via Fastlane)
        script: |
          # Create an Auth Key file for Fastlane using Python to ensure valid JSON
          mkdir -p fastlane_auth
          python3 -c 'import json, os; open("fastlane_auth/api_key.json", "w").write(json.dumps({"key_id": os.environ["APP_STORE_CONNECT_KEY_IDENTIFIER"], "issuer_id": os.environ["APP_STORE_CONNECT_ISSUER_ID"], "key": os.environ["APP_STORE_CONNECT_PRIVATE_KEY"], "in_house": False}))'
          
          # Use Fastlane to "Cert" (Create/Fetch Certificate) and "Sigh" (Create/Fetch Profile)
          gem install fastlane # Ensure latest
          
          # 1. Register App ID (and create App Store entry)
          fastlane run produce app_identifier:"$BUNDLE_ID" app_name:"Lift 14 AI" language:"en-US" api_key_path:"fastlane_auth/api_key.json"
          
          # 2. Get Certificate
          fastlane run get_certificates api_key_path:"fastlane_auth/api_key.json" generate_apple_certs:true
          
          # 3. Get Profile
          fastlane run get_provisioning_profile app_identifier:"$BUNDLE_ID" api_key_path:"fastlane_auth/api_key.json" force:true
          fastlane run get_provisioning_profile app_identifier:"$BUNDLE_ID" api_key_path:"fastlane_auth/api_key.json" force:true
      - name: Use signing files
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -exec dir {} \;
          cd ios && pod install
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
      - name: Publish to TestFlight
        script: |
          app-store-connect publish --path $(find build/ios/ipa -name "*.ipa")
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
