workflows:
  ios-workflow:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple
      vars:
        BUNDLE_ID: com.orizg.lift14
    scripts:
      - name: Set up keychain to be active
        script: |
          keychain initialize
      - name: Fetch signing files (via Fastlane)
        script: |
          # 0. Get the active keychain (set up by Codemagic)
          # We must put certs here so they are unlocked and available to xcodebuild
          KEYCHAIN_PATH=$(security default-keychain | xargs)
          echo "Using Keychain: $KEYCHAIN_PATH"
          
          # Create an Auth Key file
          mkdir -p fastlane_auth
          python3 -c 'import json, os; open("fastlane_auth/api_key.json", "w").write(json.dumps({"key_id": os.environ["APP_STORE_CONNECT_KEY_IDENTIFIER"], "issuer_id": os.environ["APP_STORE_CONNECT_ISSUER_ID"], "key": os.environ["APP_STORE_CONNECT_PRIVATE_KEY"], "in_house": False}))'
          
          # Install Fastlane & Spaceship
          gem install fastlane
          gem install spaceship
          
          # 1. Export Auth for ALL Fastlane tools
          export APP_STORE_CONNECT_API_KEY_PATH=$PWD/fastlane_auth/api_key.json
          
          # 2. AUTOMATED CLEANUP & SETUP (Ruby/Spaceship)
          cat > cleanup.rb <<EOF
          require 'spaceship'
          puts "🚀 Starting Auto-Cleanup..."
          key_path = ENV['APP_STORE_CONNECT_API_KEY_PATH']
          token = Spaceship::ConnectAPI::Token.from_json_file(key_path)
          Spaceship::ConnectAPI.token = token
          
          # A) Revoke Excess Certificates
          puts "🔍 Scanning Certificates..."
          ['IOS_DISTRIBUTION', 'DISTRIBUTION'].each do |type|
            Spaceship::ConnectAPI::Certificate.all(filter: {certificateType: type}).each do |c|
              puts "  - Revoking old cert (#{type}): #{c.id}"
              c.delete!
            end
          end
          puts "✅ Certificates cleared. Waiting 5s..."
          sleep 5
          
          # B) Ensure App ID Exists
          bid = '$BUNDLE_ID'
          puts "🔍 Checking App ID: #{bid}..."
          existing = Spaceship::ConnectAPI::BundleId.all(filter: {identifier: bid}).first
          if existing
             puts "  - App ID exists."
          else
             Spaceship::ConnectAPI::BundleId.create(identifier: bid, name: 'Lift 14 AI', platform: 'IOS')
             puts "✅ App ID Created."
          end
          EOF
          
          ruby cleanup.rb
          
          # 3. Get Certificate (Install into the ACTIVE keychain)
          fastlane run get_certificates generate_apple_certs:true keychain_path:"$KEYCHAIN_PATH"
          
          # 4. Get Profile
          fastlane run get_provisioning_profile app_identifier:"$BUNDLE_ID" force:true
          
      - name: Set up code signing settings on Xcode project
        script: |
          gem install fastlane
          # Force "Apple Distribution" Identity and Manual Signing
          fastlane run update_code_signing_settings use_automatic_signing:false targets:"Runner" path:"ios/Runner.xcodeproj" code_sign_identity:"Apple Distribution"
          fastlane run update_project_provisioning profile:"$BUNDLE_ID AppStore" target:"Runner" build_configuration:"Release" path:"ios/Runner.xcodeproj"
          
          # Generate Export Options Plist
          cat > ios/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$BUNDLE_ID AppStore</string>
            </dict>
          </dict>
          </plist>
          EOF
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
          # Force generation of ios/Flutter/Generated.xcconfig
          flutter build ios --config-only --no-codesign
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Build IPA (Flutter Build + Fastlane Gym)
        script: |
          # 1. Build Flutter assets (No signing)
          flutter build ios --release --no-codesign
          
          # 2. Extract Team ID from the Profile we just fetched
          # (Xcode needs the Team ID for manual signing, so we extract it from the valid profile)
          PROFILE_PATH=$(find . -maxdepth 1 -name "*.mobileprovision" | head -n 1)
          if [ -z "$PROFILE_PATH" ]; then
            echo "❌ No mobileprovision file found in root!"
            exit 1
          fi
          echo "Found Profile: $PROFILE_PATH"
          
          # Decode the profile and extract TeamIdentifier[0]
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print TeamIdentifier:0" /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          echo "✅ Detected Team ID: $TEAM_ID"
          
          # 3. Archive & Export IPA using Fastlane Gym
          gem install fastlane
          fastlane run build_app \
            workspace:"ios/Runner.xcworkspace" \
            scheme:"Runner" \
            export_method:"app-store" \
            export_options:"ios/export_options.plist" \
            output_directory:"build/ios/ipa" \
            output_name:"Lift14.ipa" \
            clean:true \
            xcargs:"PROVISIONING_PROFILE_SPECIFIER='$BUNDLE_ID AppStore' CODE_SIGN_STYLE='Manual' CODE_SIGN_IDENTITY='Apple Distribution' DEVELOPMENT_TEAM='$TEAM_ID'"
            
      - name: Publish to TestFlight
        script: |
          app-store-connect publish --path "build/ios/ipa/Lift14.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
