workflows:
  ios-workflow:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple
      vars:
        BUNDLE_ID: com.orizg.lift14
    scripts:
      - name: Set up keychain to be active
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          
          # Debug: Check Key Format (Safe, only prints headers)
          echo "🔑 Checking Private Key Format..."
          KEY_HEADER=$(echo "$APP_STORE_CONNECT_PRIVATE_KEY" | head -n 1)
          KEY_FOOTER=$(echo "$APP_STORE_CONNECT_PRIVATE_KEY" | tail -n 1)
          echo "Header: $KEY_HEADER"
          echo "Footer: $KEY_FOOTER"
          
          if [[ "$KEY_HEADER" != "-----BEGIN PRIVATE KEY-----" ]]; then
             echo "❌ ERROR: Private Key header is incorrect! Found: $KEY_HEADER"
          fi
          
          # Standard Fetch
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use signing files
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -exec dir {} \;
          cd ios && pod install
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
      - name: Publish to TestFlight
        script: |
          app-store-connect publish --path $(find build/ios/ipa -name "*.ipa")
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
